### ISSUE TITLE
Вакансия frontend-developer

### ISSUE THREAD

**Issue by sberez** [Valyay/ev-spa#1]
###### **Привет, Евгений**!
Я обратила внимание, что Вы интересуетесь  JS и имеете опыт работы с React и TypeScript. А у нас есть подходящая вакансия - https://spb.hh.ru/vacancy/34469941
**Что нужно делать** :
-Проектирование и разработка Front-End с использованием Angular 8+
-Верстка и дизайн страниц
-Написание unit-тестов
**Необходим опыт работы с JS, HTML5, TypeScript и Angular (если не знаете Angular - можно попробовать изучить его во время выполнения тестового задания).**
_Если наше предложение Вам интересно, перезвоните, пожалуйста, в рабочее время по телефону +7 (812) 4490027 (Березовская Светлана) или ответьте на это сообщение https://t.me/sb_spb - я свяжусь с Вами для обсуждения деталей._

**Comment by mrexox** [comment]
Что конкретно вам не нравится в этом проекте? 🤔

**Comment by Valyay** [comment]
До свидания
